/**
 * AUTO-GENERATED by scripts/deploy.ts — do not edit by hand.
 * Embedded copies of contracts/deployments/<network>.json so serverless
 * bundles (Vercel) always ship the current addresses without relying on
 * filesystem reads or hand-maintained env vars.
 */
export const EMBEDDED_DEPLOYMENTS: Record<string, {
  chainId: number;
  NexusAgent: string;
  ProofMeshReceipts: string;
  NexusEscrow: string;
  ReputationRegistry: string;
  CompositeReceiptMinter: string;
  trustedSigner: string;
} | null> = {
  galileo: {
    chainId: 16602,
    NexusAgent: "0x8B1BB4B8E6c7c3484FA6DECC360B9FC63dBf2D78",
    ProofMeshReceipts: "0x1bE84724492C94124F166904E54A3F9e289A4814",
    NexusEscrow: "0xE85c91123734FEABABF547C5f08b8E433D119BF4",
    ReputationRegistry: "0xaA2292341aEe457a2dE3f535006A8F47aE5a8625",
    CompositeReceiptMinter: "0xf6e60F3130774051e12C697cc87682293A0FCDc2",
    trustedSigner: "0x2f737521b9b59c202e7d33509C5746A58D795870",
  },
  mainnet: {
    chainId: 16661,
    NexusAgent: "0x7D4eD6c120E41a241973760D8aD244f2f9Ec6793",
    ProofMeshReceipts: "0x709D50F09527b7a3AdC041dFA387f39151535A36",
    NexusEscrow: "0xB93c13b4Dbe322dF7B8051501A8E753f1A4Cd703",
    ReputationRegistry: "0xc04012c6586eaF48726D37206502682375e63137",
    CompositeReceiptMinter: "0x8Ecb868cFF8B9B809bB5318467b0C20d1d518c58",
    trustedSigner: "0x2f737521b9b59c202e7d33509C5746A58D795870",
  },
};
