// Extracts ABIs from Foundry artifacts (contracts/out) into src/abis.ts so the
// TypeScript SDK and the frontend always use the compiled contract interface.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../../../contracts/out");
const DEST = resolve(__dirname, "../src/abis.ts");

const NAMES = [
  "NexusAgent",
  "ProofMeshReceipts",
  "NexusEscrow",
  "ReputationRegistry",
  "CompositeReceiptMinter",
];

let body = `// AUTO-GENERATED by scripts/extract-abis.mjs — do not edit by hand.\n/* eslint-disable */\n`;
for (const name of NAMES) {
  const p = resolve(OUT, `${name}.sol/${name}.json`);
  if (!existsSync(p)) {
    console.error(`! missing artifact ${p} — run 'forge build' first`);
    process.exit(1);
  }
  const artifact = JSON.parse(readFileSync(p, "utf8"));
  body += `export const ${name}ABI = ${JSON.stringify(artifact.abi)} as const;\n`;
}
writeFileSync(DEST, body);
console.log(`wrote ${DEST} (${NAMES.length} ABIs)`);
