/**
 * Re-emit packages/sdk/src/deployments.generated.ts from the deployment JSONs
 * (shared by deploy.ts and deploy-erc8004.ts). Extra keys (ERC-8004 layer)
 * flow through automatically.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ok } from "./_common.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export function regenerateEmbedded(): void {
  const nets = ["galileo", "mainnet"] as const;
  const entries = nets.map((n) => {
    const p = resolve(ROOT, `contracts/deployments/${n}.json`);
    if (!existsSync(p)) return `  ${n}: null,`;
    const d = JSON.parse(readFileSync(p, "utf8"));
    return `  ${n}: {\n${Object.entries(d)
      .map(([k, v]) => `    ${k}: ${typeof v === "number" ? v : JSON.stringify(v)},`)
      .join("\n")}\n  },`;
  });
  const src = `/**
 * AUTO-GENERATED by scripts/deploy.ts / deploy-erc8004.ts — do not edit by hand.
 * Embedded copies of contracts/deployments/<network>.json so serverless
 * bundles (Vercel) always ship the current addresses without relying on
 * filesystem reads or hand-maintained env vars.
 */
import type { Deployments } from "./config.js";

export const EMBEDDED_DEPLOYMENTS: Record<string, Deployments | null> = {
${entries.join("\n")}
};
`;
  writeFileSync(resolve(ROOT, "packages/sdk/src/deployments.generated.ts"), src);
  ok("regenerated packages/sdk/src/deployments.generated.ts");
}
